"""add_issue_exclusions_table

Revision ID: 43c49dbfd21c
Revises: 5add138ff697
Create Date: 2026-01-17 12:49:00.314825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "43c49dbfd21c"
down_revision: Union[str, None] = "5add138ff697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_exclusions",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("check_type", sa.String(length=50), nullable=False),
        sa.Column("issue_identifier", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("issue_snapshot", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("excluded_by", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["evaluation_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issue_exclusions_check_type"), "issue_exclusions", ["check_type"], unique=False)
    op.create_index(op.f("ix_issue_exclusions_id"), "issue_exclusions", ["id"], unique=False)
    op.create_index(op.f("ix_issue_exclusions_report_id"), "issue_exclusions", ["report_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_exclusions_report_id"), table_name="issue_exclusions")
    op.drop_index(op.f("ix_issue_exclusions_id"), table_name="issue_exclusions")
    op.drop_index(op.f("ix_issue_exclusions_check_type"), table_name="issue_exclusions")
    op.drop_table("issue_exclusions")
    # ### end Alembic commands ###
