"""create bpmn_models table

Revision ID: 9ef24e42fac7
Revises:
Create Date: 2025-11-18 16:12:19.167621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ef24e42fac7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bpmn_models",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bpmn_models_file_path"), "bpmn_models", ["file_path"], unique=True)
    op.create_index(op.f("ix_bpmn_models_id"), "bpmn_models", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bpmn_models_id"), table_name="bpmn_models")
    op.drop_index(op.f("ix_bpmn_models_file_path"), table_name="bpmn_models")
    op.drop_table("bpmn_models")
    # ### end Alembic commands ###
