"""replace_step_columns_for_parallel_execution

Revision ID: e1bb6a9eec4e
Revises: 1139be350900
Create Date: 2026-01-18 11:15:30.568684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1bb6a9eec4e"
down_revision: Union[str, None] = "1139be350900"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses", sa.Column("step_duplicate_check", sa.String(length=20), nullable=False, server_default="running")
    )
    op.add_column(
        "analyses",
        sa.Column("step_semantic_label_check", sa.String(length=20), nullable=False, server_default="running"),
    )
    op.add_column(
        "analyses", sa.Column("step_complexity_check", sa.String(length=20), nullable=False, server_default="running")
    )
    op.add_column(
        "analyses", sa.Column("step_custom_checks", sa.String(length=20), nullable=False, server_default="running")
    )
    op.add_column(
        "analyses", sa.Column("step_validation_check", sa.String(length=20), nullable=False, server_default="running")
    )
    op.add_column(
        "analyses", sa.Column("step_overall_evaluation", sa.String(length=20), nullable=False, server_default="running")
    )
    op.drop_column("analyses", "current_step")
    op.drop_column("analyses", "steps_completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses",
        sa.Column(
            "steps_completed",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("analyses", sa.Column("current_step", sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column("analyses", "step_overall_evaluation")
    op.drop_column("analyses", "step_validation_check")
    op.drop_column("analyses", "step_custom_checks")
    op.drop_column("analyses", "step_complexity_check")
    op.drop_column("analyses", "step_semantic_label_check")
    op.drop_column("analyses", "step_duplicate_check")
    # ### end Alembic commands ###
